name: Python Syntax Check

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
      - '!README.md'

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          since_last_remote_commit: 'true'

      - name: Install dependencies
        run: pip install pytest

      - name: Run Python syntax check
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, '.py') }}
        run: |
          echo "Проверяем файлы: ${{ steps.changed-files.outputs.all_changed_files }}"
          python -m py_compile ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run TSP tests
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, 'prob.py') || contains(steps.changed-files.outputs.all_changed_files, 'test_tsp.py') }}
        run: |
          echo "Запуск тестов для TSP..."
          pytest tests/test_tsp.py -v

      - name: Run main script
        if: ${{ contains(steps.changed-files.outputs.all_changed_files, 'prob.py') }}
        run: python prob.py